# Generated by Django 6.0.7 on 2026-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
